name: event_display_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # You can adjust this version as needed
  - numpy
  - awkward
  - uproot
  - pyvista
  - pip
  - pip:
      - vtk