name: event_display
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # You can adjust this version as needed
  - numpy
  - awkward
  - uproot
  - pyvista
  - cloudpickle  # `pickle` is part of Python's standard library, but `cloudpickle` extends it for distributed tasks
  - pip
  - pip:
      - vtk